# Generated by Django 5.0 on 2024-01-09 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cartitem_is_paid_cartitem_razor_pay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='razor_pay_order_id',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='razor_pay_payment_id',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='razor_pay_payment_signature',
        ),
    ]
