# Generated by Django 5.0 on 2024-01-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cartitem',
        ),
        migrations.AddField(
            model_name='order',
            name='cartitem',
            field=models.ManyToManyField(to='products.cartitem'),
        ),
    ]
