# Generated by Django 5.0 on 2024-01-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_order_cartitem_order_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cartitem',
        ),
        migrations.AddField(
            model_name='order',
            name='cartitem',
            field=models.ManyToManyField(to='products.cartitem'),
        ),
    ]
