# Generated by Django 5.0 on 2024-01-10 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_order_cartitem_order_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cartitem',
        ),
    ]
